FROM ruby:3.4.8

WORKDIR /app

RUN apt-get update -y && apt-get install -y build-essential libpq-dev nodejs && rm -rf /var/lib/apt/lists/*

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000
CMD ["bash", "-lc", "bin/rails s -b 0.0.0.0 -p 3000"]